config/routes.rb
Rails.application.routes.draw do

  get 'follows/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/show'
  get 'users/index'
  get 'profiles/index'
  get 'profiles/show'
  get 'profiles/create'
  get 'profiles/new'
  get 'profiles/edit'
  get 'profiles/update'
  get 'profiles/destroy'
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    get 'auth/:provider/callback', to: 'sessions#googleAuth'
    get 'auth/failure', to: redirect('/')

   devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    # root to: 'users/sessions#new'
    get 'sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
    get 'users/edit' => 'users/registrations#edit'
    get 'users/sign_up' => 'users/registrations#new'

  end

    resources :users do
      member do
        get :following, :followers
        post 'follow', to: "users#follow"
        post 'unfollow', to: "users#unfollow"
      end
    end


  resources :profiles
  
  resources :articles do
    collection do 
      get "tag_articles", to: "articles#tag_articles"
      get "own_articles", to: "articles#own_articles"
      get "trending_articles", to: "articles#trending_articles"
    end

    member do
      patch "upvote", to: "articles#upvote"
      patch "downvote", to: "articles#downvote"
   end
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  get 'search', to: "application#search"
  root to: 'articles#index'


end

app/models/article.rb
class Article < ApplicationRecord
  # ransack_alias :any_column, User.column_names.excluding('id', 'created_at', 'updated_at').join('_or_')
  acts_as_votable
  belongs_to :user
  has_rich_text :body
  has_one :action_text_rich_text,  class_name: 'ActionText::RichText',   as: :record
  has_many :comments, as: :commentable
  has_many :taggings
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :tags,  reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
  validates :title, presence: true, length: { maximum: 100}
  validates :body, presence: true
  attribute :viewed, :integer, default: 0
  enum status: [ :draft, :published ]



  def self.published_articles_in_week
    Article.where(created_at: Time.now.to_date - 7.days..Time.now).published.order("created_at DESC")
  end

  def self.published_articles_in_month
    Article.where(created_at: Time.now.to_date - 1.month..Time.now).published.order("created_at DESC")
  end

  def self.top_view(articles)
    if articles.class != Article
      articles.published.reorder(viewed: :desc)
    else
      articles
    end
  end

  def self.top_like(articles)
    if articles.class != Article
      articles.published.reorder("cached_votes_total DESC")
    else
      articles
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :upvote , :downvote]
    after_action :count_viewed, only: :show
    
    
    def upvote

        if current_user.voted_up_on? @article
          @article.unvote_by current_user
        else
          @article.upvote_by current_user
        end
        render "vote.js.erb"

    end
  
    def downvote
      
        if current_user.voted_down_on? @article
          @article.unvote_by current_user
        else
          @article.downvote_by current_user
        end
        render "vote.js.erb"
      
    end

def index
    
  @filter_datas = Article.published.order("created_at DESC")
    if !params[:times].blank?
      case params[:times]
      when 'week'
        @filter_datas = Article.published_articles_in_week
      when 'month'
        @filter_datas = Article.published_articles_in_month
      end
    end
    if !params[:orders].blank?
      case params[:orders]
      when 'view'       
        @filter_datas = Article.top_view(@filter_datas) 
      when 'like'
        @filter_datas = Article.top_like(@filter_datas) 
      end     
    end
    @q = @filter_datas.ransack()
    @articles = @q.result(:distinct=>true)
    # @articles = Article.published.order("created_at DESC")
end

def own_articles
    # @articles = current_user.articles.order("created_at DESC")
    if !params[:user_id].blank?
      @q = User.find_by(id: params[:user_id]).articles.published.order("created_at DESC").ransack()  
      @articles = @q.result(:distinct=>true)
    elsif !params[:user_id].blank? and current_user == params[:user_id]
      @q = current_user.articles.published.order("created_at DESC").ransack()  
      @articles = @q.result(:distinct=>true)      
    end
    render "index"
end

def trending_articles
  @q = Article.published.order("viewed DESC, created_at DESC").ransack()  
  @articles = @q.result(:distinct=>true)
# get top articles by liked
# @articles = Article.published.order("cached_votes_total DESC, created_at DESC")
  render "index"
end

def tag_articles
  if user_signed_in?
    @q = Article.joins(:tags).where("(tags.name = ? and status = 1) or (tags.name = ? and user_id = ?)", params[:tag],params[:tag], current_user.id ).order("created_at DESC").ransack()  
  else
    @q = Article.joins(:tags).where("tags.name = ? and status = 1", params[:tag]).order("created_at DESC").ransack()  
  end
  @articles = @q.result(:distinct=>true)
  # @articles = Article.joins(:tags).where("tags.name = ?", params[:tag]).published.order("created_at DESC")
  render "index"
end

def show

end





def new
    @article = Article.new
end

def create
 
    @article = current_user.articles.new(article_params.except(:tags))
    if !params["article"][:tags].blank?
      params["article"][:tags].shift()
      params["article"][:tags].each do |t|
        tag = Tag.find_or_create_by(name: t)
        @article.tags << tag
      end  
    end
    respond_to do |format|
        if @article.save
          
          format.html { redirect_to @article, notice: 'Tạo mới thành công.' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
end

def edit

end

def update
  if !params["article"][:tags].blank?
    params["article"][:tags].shift()
    params["article"][:tags].each do |t|
      tag = Tag.find_or_create_by(name: t)
      @article.tags << tag
    end  
  end
    respond_to do |format|
        if @article.update(article_params.except(:tags))
          format.html { redirect_to @article, notice: 'Update thành công.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
end

def destroy
    @article.destroy
    respond_to do |format|
        format.html { redirect_to own_articles_articles_path, notice: 'Đã xóa.' }
        format.json { head :no_content }
      end
end

private

def set_article
    @article = Article.find_by(id: params[:id])
end
# tags_attributes: [:name, ]
def article_params
    arti_params = params.require(:article).permit(:title, :body, :user_id, :viewed, :status, tags: [])
    arti_params[:status] = params[:article][:status].to_i
    return arti_params
end

def count_viewed
  set_article
  @article.viewed += 1
  @article.save
end



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{article.id}" do %>
  <% if user_signed_in? %>
    <%= link_to downvote_article_path(article), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
      <% if current_user.voted_down_on? article %>
        <i class="fas fa-thumbs-down"></i>
      <% else %>
        <i class="far fa-thumbs-down"></i>
      <% end %>
      <%= article.get_downvotes.size %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
      <i class="far fa-thumbs-down"></i>
      <%= article.get_downvotes.size %>
    <% end %>
  <% end %>
<% end %>

app/views/articles/_form.html.erb
<div class="container" style="width: 1000px">
  <br>
  <%= form_with(model: article) do |form| %>
    <% if article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group row">
      <div class="col-sm-12">
        <div class="field">
          <%= form.label :title%>
          <%= form.text_field :title, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-8">
        <div class="field">
          <%= form.label :tags %>
          <%= form.select  :tags, Tag.all.pluck(:name) , { include_blank: true }, {  :class => 'bt-select2',multiple: "multiple" } %>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2"> Status:</label>
      <div class="form-check">
        <%= form.label :status, "Draft", class: 'form-check-label' %>
        <%= form.radio_button :status, 0, checked: (article.status == "draft")  %>
      </div>
      <div class="form-check">
        <%= form.label :status, "Published", class: 'form-check-label'%>
        <%= form.radio_button :status, 1, checked: (article.status == "published")%>
      </div>
    </div>
    <div class="field">
      <%= form.label :body %>
      <%= form.rich_text_area :body , class: 'form-control' %>
    </div>
    <div class="actions">
   
      <%= form.submit %>
       <%= link_to 'Back', :back, class: 'btn' %>
    </div>
  <%end%>
</div>

app/views/articles/_index.html.erb
<style>
  .align {
    text-align: right;
    align-items: right;
    justify-content: right;
  }
</style>
<div class="container">
  <ul class="list-unstyled">
    <%= render "articles/order_by_params", article: @articles if current_page?(root_path) || current_page?(articles_path)  %>
    <% if articles != nil %>
      <% articles.each do |article|%>
        <li class="media">
          <div class="form-group row">
            <div class="col-sm-4">
              <% if article.user.profile.avatar.attached? %>
                <%= image_tag article.user.profile.avatar.variant(resize: "40x40!"), class: "rounded-circle" %>
              <% else %>
                <%= image_tag 'index.png', alt:'avatar', width:"40", height:"40", class: "rounded-circle"%>
              <% end%>
              <% if article.user.username? %>
                <%= link_to article.user.username, article.user %>
              <%else%>
                <%= link_to article.user.email.truncate(9, omission: '..'), article.user %>
              <%end%>
              <%= render "users/follow", user: article.user %>
            </div>
          </div>
          <%# <img class="mr-3" src="..." alt="Generic placeholder image"> %>
          <div class="media-body">
            <div class='row'>
              <div class="col-lg-9 ">
                <h5 class="mt-0 mb-1"> <b> <%= link_to article.title, article %> </b></h5>
              </div>
              <div class="col-lg-3 align ">
                State: <%= article.status %>
                <%= link_to  edit_article_path(article) do %> <i class="fas fa-edit"></i><% end %> |
                <%= link_to  article, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fas fa-trash-alt"></i> <% end %>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-lg-6 ">
                <div class="row">
                  <i class="fas fa-eye has-tooltip" title="Viewed">  <%= article.viewed %>  </i>
                  <i class="fa fa-comments has-tooltip" title="Commened">  <%= article.comments.count + article.comments.map{|e| e.comments}.flatten.count %>  </i>
                </div>
              </div>
              <div class="col-lg-6 align">
                <% if (Time.now - 2.days) < article.created_at %>
                  Posted at: <%= distance_of_time_in_words(Time.now, article.created_at) %> ago
                <% else %>
                  Posted at: <%= article.created_at %>
                <% end%>
              </div>
            </div>
            <div class="trix-content">
              <%= article.body.to_plain_text.truncate(200, omission: '...') %> <%= link_to '(continuous reading)', article%>
            </div>
            <div class="form-group row">
              <div class="col-lg-4 ">
                <div class="row">
                  <td><%= render "articles/upvote_link", article: article %></td>
                  <td><%= render "articles/downvote_link", article: article %></td>
                </div>
              </div>
              <div class="col-lg-8 ">
                <div class="row align">
                  Tag: 
                  <% article.tags.each do |tag|%>
                    <%= link_to tag.name, tag_articles_articles_path(:tag => tag.name) %>|
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </li>
        <hr class="filler-line mb-05">
      <% end %>
    <% end %>
  </ul>
</div>

app/views/articles/_info_article_form.html.erb
<style>
  .align {
    text-align: right;
    align-items: right;
    justify-content: right;
  }
</style>
<div class="row ">
  <%# <div class="column">
        <%= user.profile.avatar %>
  <%# </div> %>
  <div class="col-lg-6 ">
    <% if article.user.profile.avatar.attached? %>
      <%= image_tag article.user.profile.avatar.variant(resize: "40x40!"), class: "rounded-circle" %>
    <% else %>
      <%= image_tag 'index.png', alt:'avatar', width:"40", height:"40", class: "rounded-circle"%>
    <% end%>
    <% if article.user.username? %>
      Author: <%= link_to article.user.username, article.user  %>
    <%else%>
      Author: <%= link_to article.user.email, article.user %>
    <%end%>
     <%= render "users/follow", user: article.user %>
  </div>
  <div class="col-lg-6 align">
    <% if (Time.now - 2.days) < article.created_at %>
      Posted at: <%= distance_of_time_in_words(Time.now, article.created_at) %> ago
    <% else %>
      Posted at: <%= article.created_at %>
    <% end%>
    <div class="row align">
      <i class="fas fa-eye has-tooltip" title="Viewed">  <%= article.viewed %>  </i>
      <i class="fa fa-comments has-tooltip" title="Commened">  <%= article.comments.count + article.comments.map{|e| e.comments}.flatten.count %>  </i>
      <td><%= render "articles/upvote_link", article: article %></td>
      <td><%= render "articles/downvote_link", article: article %></td>
    </div>
  </div>
</div>

app/views/articles/_order_by_params.html.erb
<style>
  .align {
    text-align: right;
    align-items: right;
    justify-content: right;
  }
</style>
<div class="row align">
 <%= link_to 'All', articles_path %>|
  <%= link_to 'Week', articles_path(:times => "week")  %>|
  <%= link_to 'Month', articles_path(:times => "month")  %>|
  <% if !params[:times].blank? %>
    <%= link_to 'Most Viewed', articles_path(:orders => "view", :times => params[:times])   %>|
    <%= link_to 'Most Liked', articles_path(:orders => "like", :times => params[:times])  %>
  <% else %>
    <%= link_to 'Most Viewed', articles_path(:orders => "view")   %>|
    <%= link_to 'Most Liked', articles_path(:orders => "like")  %>
  <% end %>
</div>

app/views/articles/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{article.id}" do %>
    <% if user_signed_in? %>
        <%= link_to upvote_article_path(article), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
            <% if current_user.voted_up_on? article %>
            <i class="fas fa-thumbs-up"></i>
            <% else %>
            <i class="far fa-thumbs-up"></i>
            <% end %>
            <%= article.get_upvotes.size %>
        <% end %>
    <% else %>
        <%= link_to upvote_article_path(article), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
          
            <i class="far fa-thumbs-up"></i>
           
            <%= article.get_upvotes.size %>
        <% end %>
    <% end %>
<% end %>

app/views/articles/_votes_score.html.erb
<%= content_tag "div", id: "votes-score-#{article.id}" do %>
  <%= article.cached_votes_score %>
<% end %>

app/views/articles/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<div class="container">
<br>
<h4> Edit Article </h4>
<%= render 'form' , article: @article %>
</div>

<script type="text/javascript">
    $(document).ready(function() {
    $('.bt-select2').each(function() {
            $(this).select2({
                maximumInputLength: 15,
                maximumSelectionLength: 5,
                tags: true,
                width: '100%',
                allowClear: true   // Shows an X to allow the user to clear the value.
            });
        });
     });
    
</script>

app/views/articles/index.html.erb
<br>
<%=  render "articles/index", articles: @articles %>

app/views/articles/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<div class="container">
<br>
<h4> Create new Article </h4>
<%= render 'form' , article: @article %>
</div>

<script type="text/javascript">
    $(document).ready(function() {
    $('.bt-select2').each(function() {
            $(this).select2({
                maximumInputLength: 15,
                maximumSelectionLength: 3,
                tags: true,
                width: '100%',
                allowClear: true   // Shows an X to allow the user to clear the value.
            });
        });
     });
    
</script>

app/views/articles/show.html.erb
<div  class="container">
  <div class="row pt-3 pb-1">
    <div class="col-lg-9 pl-md-0">
      <%= render partial: "info_article_form", locals: {article: @article} %>
      <br>
      <p><strong> <%= @article.title %></strong>  </p>
      <br>
      <p>
        
        <div class="trix-content">
          <%= @article.body %>
        </div>
      </p>
      <hr class="filler-line mb-05">
      <p>
        <h5 class="text-bold"> TAG </h5>
        <% @article.tags.each do |tag|%>
          <%= link_to tag.name, tag_articles_articles_path(:tag => tag.name) %>|
        <% end %>
      </p>
       <p>
        <strong>Viewed:</strong>
        <%= @article.viewed %>
      </p>
         <%= link_to 'Edit', edit_article_path(@article) %> |
      <%= link_to 'Back', articles_path %>
      <%# <%= link_to "Back", :back %> 
      <% if @article.comments != nil %>
        <div class="section-title-line mr-lg-n1">
          <h4 class="text-bold">
            <%= @article.comments.count + @article.comments.map{|e| e.comments}.flatten.count %> CÂU TRẢ LỜI
          </h4>
       
 <hr class="filler-line mb-05">
        </div>
        <%= render partial: "comments/comments", locals: {commentable: @article} %>
      <% end%>
      <% if user_signed_in? %>
        <%= render partial: "comments/form", locals: {commentable: @article} %>
        <% else %>
        <%= link_to 'Sign in to comment', new_user_session_path %>
      <% end %>
     
      
    </div>
  </div>
</div>

app/views/articles/vote.js.erb
document.getElementById("upvote-<%= @article.id %>").innerHTML = "<%= j render "articles/upvote_link", article: @article %>";
document.getElementById("downvote-<%= @article.id %>").innerHTML = "<%= j render "articles/downvote_link", article: @article %>";