config/routes.rb
Rails.application.routes.draw do

  get 'follows/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/show'
  get 'users/index'
  get 'profiles/index'
  get 'profiles/show'
  get 'profiles/create'
  get 'profiles/new'
  get 'profiles/edit'
  get 'profiles/update'
  get 'profiles/destroy'
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    get 'auth/:provider/callback', to: 'sessions#googleAuth'
    get 'auth/failure', to: redirect('/')

   devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    # root to: 'users/sessions#new'
    get 'sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
    get 'users/edit' => 'users/registrations#edit'
    get 'users/sign_up' => 'users/registrations#new'

  end

    resources :users do
      member do
        get :following, :followers
        post 'follow', to: "users#follow"
        post 'unfollow', to: "users#unfollow"
      end
    end


  resources :profiles
  
  resources :articles do
    collection do 
      get "tag_articles", to: "articles#tag_articles"
      get "own_articles", to: "articles#own_articles"
      get "trending_articles", to: "articles#trending_articles"
    end

    member do
      patch "upvote", to: "articles#upvote"
      patch "downvote", to: "articles#downvote"
   end
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  get 'search', to: "application#search"
  root to: 'articles#index'


end

app/models/role.rb
class Role < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter 
  has_one :profile, dependent:   :destroy
  has_many :articles
  has_and_belongs_to_many :roles
  #  following of user
  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent:   :destroy
  has_many :followings, through: :active_follows, source: :followed
  #  user's follower
  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent:   :destroy
  has_many :followers, through: :passive_follows, source: :follower

  validates :username, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: true }

  after_create :set_defaul_role
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :trackable, :lockable, :omniauthable, authentication_keys: [:login], omniauth_providers: [:google_oauth2] 

        #  def self.from_google(email:, full_name:, uid:, avatar_url:)
          # return nil unless email =~ /@gmail.com\z/
          # create_with(uid: uid, full_name: full_name, avatar_url: avatar_url, password: Devise.friendly_token[0,20]).find_or_create_by!(email: email)
        def self.from_omniauth(auth)
          user = User.find_by(email: auth.info.email)
          if user and user.confirmed?
            user.provider = auth.provider
            user.uid = auth.uid
            return user
          end
        
          where(auth.slice(:provider, :uid)).first_or_create do |user|
            user.skip_confirmation! 
            user.provider = auth.provider
            user.uid = auth.uid
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            user.full_name = auth.info.name
          end
        end
        
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      # where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end

  def get_user_info
    self.username? ? self.username : self.email
  end

  def set_defaul_role
    self.roles << Role.find_by(role: 'normal_user')
  end
  def add_defaul_profile
    @profile = self.build_profile()
    @profile.save
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
   def google_oauth2
    # byebug
    # user = User.from_google(email: from_google_params[:email],uid: from_google_params[:uid],full_name: from_google_params[:full_name],avatar_url: from_google_params[:avatar_url])
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user , event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      puts (" failllllllllleddddd")
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
     root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected


  def after_sign_up_path_for(resource)
     url = session[:fall_back_url]
       session[:fall_back_url] = nil
      if current_user && url
        url
      end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # def googleAuth
  #   # Get access tokens from the google server
  #   access_token = request.env["omniauth.auth"]
  #   user = User.from_omniauth(access_token)
  #   log_in(user)
  #   # Access_token is used to authenticate request made from the rails application to the google server
  #   user.google_token = access_token.credentials.token
  #   # Refresh_token to request new access_token
  #   # Note: Refresh_token is only sent once during the first request
  #   refresh_token = access_token.credentials.refresh_token
  #   user.google_refresh_token = refresh_token if refresh_token.present?
  #   user.save
  #   redirect_to root_path
  # end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show,:follow,:unfollow]

  def show
    @profile = @user.profile
    @profile ||= Profile.new

  end

  def index
    if !params[:user_ids].blank?
    @users = User.where(id: params[:user_ids])
    render "index"
    end
  end

  def follow
    if !current_user.followings.include?(@user) 
      Follow.create(follower_id: current_user.id, followed_id: @user.id)
    end
    render "follow.js.erb"
  end

  def unfollow
    if current_user.followings.include?(@user) 
      @follow = Follow.find_by(follower_id: current_user.id, followed_id: @user.id)
      @follow.destroy
    end
    render "follow.js.erb"
  end


  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= content_tag "div", id: "follow-#{user.id}" do %>
  <% if user_signed_in? %>
    <% if !current_user.followings.include?(user) %>
      <%= link_to 'Follow',follow_user_path(user), method: :post, remote: true  %>
    <% else %>
      <%= link_to 'UnFollow',unfollow_user_path(user), method: :post, remote: true %>
    <% end %>
  <% else%>
   <%= link_to 'Follow', "/users/sign_in"  %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<div class="container" style="width: 1000px"> 
<%= form_with model: @user do |f| %>
    <div class="mb-3"> 
    <%= f.label :name, "ho ten"%>
    <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="mb-3"> 
    <%= f.label :email, "mail"%>
    <%= f.text_field :email, class: 'form-control' %>
    </div>
     <div class="mb-3"> 
    <%= f.label :phone, "phone"%>
    <%= f.text_field :phone, class: 'form-control' %>
    </div>
    <div class="mb-3"> 
    <%= f.label :dob ,"ngay sinh"%>
    <%= f.date_field :dob, class: 'form-control' %>
    </div>
    <div class="mb-3"> 
    <%= f.label :address ,"address"%>
    <%= f.text_area :address, class: 'form-control' %>
    </div>
    <div class="mb-3"> 
             <div class="form-check">
                <%= f.label :gender, "Nam", class: 'form-check-label'%>
                <%= f.radio_button :gender, 1 ,class: 'form-control' %>
            </div>
             <div class="form-check">
                <%= f.label :gender, "Nu", class: 'form-check-label'%>
                <%= f.radio_button :gender, 0, class: 'form-control' %>
            </div>
    </div>
    <div class="mb-3"> 
        <%= f.label :language, "ngon ngu"%>
        <% Language.all.each do |t| %>
            <div class ='row'>
            <%= f.check_box :language, {mutilple: true},t.id, nil %>
            <%= t.name %>
            </div>
        <% end %>
    </div>
    <div class="mb-3"> 
        <%= f.label :vacine, "Tiem chung" %>
        <%= f.select :vacine, [["Da tiem chung",true],["Chua tiem chung", false]],  { }, { :class => 'bt-select2'} %>
    </div>

    <%= f.submit "Submit" , class: "btn btn-success"%>
<%end%>
</div>

app/views/users/_index.html.erb
 <% if users != nil %>
<div class="container">
<h4> List User <%= params[:follow]%> </h4>
<table class="table table-vcenter table-condensed ">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Articles</th>
      <th>Follower</th>
      <th>Following</th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to user.email, user %></td>
        <td><%= link_to user.articles.published.count, own_articles_articles_path(user_id: user.id) %></td>
        <td><%= user == current_user ? (link_to user.followers.count, users_path(user_ids: user.followers.pluck(:id))) : user.followers.count%></td>
        <td><%= user == current_user ? (link_to user.followings.count, users_path(user_ids: user.followings.pluck(:id))) : user.followings.count%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', :back %>
<%= link_to 'Homepage', root_path %>
</div>
 <% end%>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/follow.js.erb
document.getElementById("follow-<%= @user.id %>").innerHTML = "<%= j render "users/follow", user: @user %>";

app/views/users/index.html.erb
<br>

<%=  render "users/index", users: @users %>

app/views/users/new.html.erb
<h1>  NEW USER  </h1>

<%= render partial: 'form', locals:{ title: 'CREATT NEW FORM'}%>

app/views/users/show.html.erb
<div  class="container">
<br>
    <h4> <%=@user.email%>'s profile </h4>  
            <%= form_with(model: @user) do |form| %>
                <div class="field">
                    <%= form.label :email %>: 
                     <%=@user.email %> 
                </div>
                <div class="field">
                    <%= form.label :username %>:
                    <%=@user.username %> 
                </div>
                <% if can? :update, @user %>
                    <%= link_to('Edit User', edit_user_registration_path , :class => "btn")%>
                <% end%>

                <div class="form-group row">
      <div class="col-sm-4">
        Followings: <%= @user.followings.blank? ?  "0" : (link_to  @user.followings.count, users_path(follow: "Following",user_ids: @user.followings.pluck(:id))) %>
         Followers: <%= @user.followers.blank? ?  "0" : (link_to  @user.followers.count, users_path(follow: "Follower",user_ids: @user.followers.pluck(:id))) %>
      </div>
    </div>
            <% end%>
           
</div>

<%= render 'profiles/form' , profile: @profile %>
 
 